### ISSUE TITLE
Incompatible with Next.js

### ISSUE THREAD

**Issue by purohitdhairy67** [mondaycom/vibe#1203] opened 2023-04-04 20:21 UTC
`./node_modules/monday-ui-react-core/node_modules/react-dates/lib/css/_datepicker.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/monday-ui-react-core/dist/esm/src/components/DatePicker/DatePicker.js

Import trace for requested module:
./node_modules/monday-ui-react-core/node_modules/react-dates/lib/css/_datepicker.css
./node_modules/monday-ui-react-core/dist/esm/src/components/DatePicker/DatePicker.js
./node_modules/monday-ui-react-core/dist/esm/src/index.js`

**Comment by orrgottlieb** [comment] 2023-04-23 11:49
Hi @purohitdhairy67 can you try the following temp version - monday-ui-react-core@1.119.1-fix-css-from-node-modeuls-6c3951cd42.0

if this helps we could push it towards production version

**Comment by Tobi042** [comment] 2023-07-27 19:47
Hi @orrgottlieb , I'll pick up here if no-one minds. 
Your version works to resolve the CSS issue, so thank you very much for this. We're still getting an error about `window` being accessed, which prevents server-side rendering and static site generation, but the biggest issue is indeed soved by this.

We can work around the SSR issue by using [Next's NoSSR mechanism](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr)

Created a CodeSandbox for demo purposes: https://codesandbox.io/p/sandbox/intelligent-vaughan-5x6m6t?file=%2Fpackage.json%3A26%2C1

I mean ideally we could get this resolved as well, but getting this fix merged would already be a great help! I would suspect the SSR is not just happening in Next either?

**Comment by orrgottlieb** [comment] 2023-07-27 21:39
Hi @Tobi042 ,im no longer leading Vibe, I'll tag the relevant people

FYI
@shlomitc @hadasfa @SergeyRoyt @YossiSaadi

**Comment by shlomitc** [comment] 2023-07-30 18:10
Hey @Tobi042 
I created a new `create-next-app` and created this example page which works.
I must say I'm not a next expert so if something doesn't make sense, please let us know

```tsx
"use client" // this is a client-side only component
import {useState} from 'react'
import 'monday-ui-react-core/tokens' // import base token styles
import { Button, DatePicker } from 'monday-ui-react-core' // import the relevant vibe components

export default function Home() {
  const [date, setDate] = useState(null);
  return (
    <div>
      <Button onClick={() => alert('hello')}>Basic Button</Button>
      <DatePicker date={date} onPickDate={setDate}/>
    </div>
  );
}

```

**Comment by Tobi042** [comment] 2023-07-31 18:15
Hi @shlomitc,

first of all let me thank you for your time spent on this issue, it is much appreciated.

It would seem that using the newly stable app router in the app removed the CSS error I get when using your library. Interestingly, it seems to be enough that the `app` directory is present to get this behavior. Very interesting... and weird... (Next.js's newer "Apps Router" can also be used to render the component client-side, but its focus is on React's new Server Components. They have only relatively recently declared it stable (in May '23). My CodeSandbox from my previous comment (and our whole codebase for that matter) is using the older and more established "Pages Router")

I think this solution to the CSS issue is probably not pretty, but okay. So I am very grateful for your support in finding it!

But to the second issue, you are forcing client-side rendering by using the `"use client"` directive, this effectively does the same as what I described as Next's NoSSR mechanism.

When I try your code, I still get a bunch of errors in next's console output (about `document` not being defined), but the render ultimately succeeds nonetheless. Can you reproduce this as well?

Is there any chance that we can get full SSR-compatibility in the lib? This would effectively mean moving all references to `window` and `document` and similar global variables that would not exist in a server-side context to `useEffect` hooks? (Of course having SSR would be more of a nice-to-have and I could understand if this was not on your list of priorities)

**Comment by shlomitc** [comment] 2023-08-01 13:42
Regarding the `document is not defined` - I opened a PR to fix this and will update here once released.
Regarding becoming fully SSR compatible - I think this would be a big task that we can't commit to at the moment, so I'm leaving it as a backlog task, but if you can assist in pushing this forward, we'll be happy to contributions.

**Comment by Tobi042** [comment] 2023-08-03 18:20
Can confirm that the `document` error is in fact gone. I'd love to try and see if I can get SSR to work, but I'll have to see when my time permits this, so I don't want to promise anything. 
In any case, thanks for the support! From my side, feel free to close the issue.

PS: Reminder for any future travelers that find this issue: The solution to get Next to compile the library past the CSS error is to create the `app` directory besides your existing `pages` directory. Don't know why exactly this works (app router enabling different behavior?), but it works.

**Comment by Dorl92** [comment] 2023-11-10 16:58
Hi @shlomitc @tobias-theobald I would like for your help.
I'm using version 2.59.1 and I get the `window` error. I tried adding an `app` directory next to `pages` directory, added `"use client"` above the components and even using Next's NoSSR mechanism but I still get the same error. 
I would be very grateful if you could help me solve this problem.

**Comment by MosheZemah** [comment] 2024-10-13 10:09
Hey @tobias-theobald , @Dorl92 
Please try to upgrade to latest version (^2.139.3) and recheck

In order to get the styles for SSR - you should initialize this on your server:
globalThis.injectedStyles

and then when creating the <head> on the server side you can do something like this:
```
function getHeadHtml(head: string) {
  let headWithInjectedStyles = head;
  if (globalThis.injectedStyles) {
    // Inject the styles into the head if globalThis.injectedStyles contains styles
    Object.keys(globalThis.injectedStyles).forEach(styleId => {
      headWithInjectedStyles += `\n<style id="${styleId}">${globalThis.injectedStyles![styleId]}</style>`;
    });
  }
  return `<head>${headWithInjectedStyles}</head>`;
}
```

**Comment by MosheZemah** [comment] 2024-10-13 10:11
Closing for now due to SSR support in latest version

**Closed by MosheZemah** 2024-10-13 10:11 UTC
